FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /opt/starship-alpha/app

RUN python -m pip install --upgrade pip

COPY . /opt/starship-alpha/app

RUN python -m pip install --no-cache-dir ./packages/starship_shared ./packages/starship_engine

CMD ["python", "-m", "starship_engine.runner"]
